"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Search
  { on = ["z"], run = "plugin finder file", desc = "Find files" },
  { on = ["Z"], run = "plugin finder dir", desc = "Find directories" },
  { on = ["g", "k"], run = "cd ~/Desktop", desc = "Go ~/Desktop" },
  { on = ["g", "p"], run = "cd ~/Projects", desc = "Go ~/Projects" },
  { on = ["g", "o"], run = "cd ~/Documents", desc = "Go ~/Documents" },
]
