[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-latte"

[mgr]
border_symbol = "Â·"
preview_hovered = { underline = false }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
