"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-latte"

[mgr]
border_symbol = "Â·"

[indicator]
preview = { underline = false }

[status]
perm_sep = { fg = "green" }
perm_type = { fg = "green" }
perm_exec = { fg = "green" }
perm_read = { fg = "green" }
perm_write = { fg = "green" }
