#################
# Custom Colors #
#################

# The single line bar at the uppermost of the display. Contains name/state/status headings etc
[colors.headers_bar]
# Background color of the entire line
background = "#1e1e2e"
# Animated loading icon at the start of the bar
loading_spinner = "#b4befe"
# Text color
text = "#cdd6f4"
# Text color of a selected header
text_selected = "#7f849c"

# The borders around the selectable panels - Containers, Commands, Logs
[colors.borders]
# Border when selected
selected = "#89dceb"
# Border when not selected
unselected = "#6c7086"

# The containers sections, in the future more color customization options should be made available in this section
[colors.containers]
# The icon use to illustrate which container is currently selected - at the moment the  TUI library, ratatui, doesn't seem allow changing the color of the highlight symbol
icon = "#cdd6f4"
# Background color of panel
background = "#1e1e2e"
# At the moment, this will only change the color of the name, id, and image columns
text = "#89b4fa"
# Text color of the RX column
text_rx = "#f9e2af"
# Text color of the TX column
text_tx = "#eba0ac"

# The logs panel, will only be applied if color_logs is false
[colors.logs]
# Background color of panel
background = "#1e1e2e"
# text color
text = "#cdd6f4"

# Each state of a container has a color, which is used in multiple places, i.e. chart titles, state/status/cpu/memory columns in the container section
[colors.container_state]
dead = "#f38ba8"
exited = "#f38ba8"
paused = "#f9e2af"
removing = "#eba0ac"
restarting = "#a6e3a1"
running_healthy = "#a6e3a1"
running_unhealthy = "#fab387"
unknown = "#f38ba8"

# The filter panel
[colors.filter]
# Background color of panel
background = "#1e1e2e"
# color of text
text = "#cdd6f4"
# background color of the selected filter by item (Name/Image/Status/All)
selected_filter_background = "#313244"
# text color of the selected filter by item (Name/Image/Status/All)
selected_filter_text = "#f5e0dc"
# Highlighted text color
highlight = "#cba6f7"


# The log search panel
[colors.log_search]
# Background color of panel
background = "#1e1e2e"
# color of text
text = "#cdd6f4"
# text color of the buttons text
button_text = "#f5e0dc"
# Highlighted text color
highlight = "#cba6f7"

# The color the of Docker commands available for each container
[colors.commands]
# Background color of panel
background = "#1e1e2e"
pause = "#f9e2af"
restart = "#cba6f7"
stop = "#f38ba8"
delete = "#6c7086"
resume = "#89b4fa"
start = "#a6e3a1"

# The cpu chart
[colors.chart_cpu]
# Background color of panel
background = "#1e1e2e"
# Border color
border = "#7f849c"
# Chart title - only whilst container is running, paused & stopped colors not yet customizable - or could just use state color?
title = "#a6e3a1"
# Maximum CPU percentage - again paused & stopped colors not yet customizable
max = "#fab387"
# Points on the chart - again paused & stopped colors not yet customizable
points = "#cba6f7"
# The charts y-axis
y_axis = "#cdd6f4"

# The memory chart
[colors.chart_memory]
# Background color of panel
background = "#1e1e2e"
# Border color
border = "#7f849c"
# Chart title - only whilst container is running, paused & stopped will use colors.container_state
title = "#a6e3a1"
# Maximum memory use - again paused & stopped will use colors.container_state
max = "#fab387"
# Points on the chart - again paused & stopped will use colors.container_state
points = "#94e2d5"
# The charts y-axis
y_axis = "#cdd6f4"

# The ports chart
[colors.chart_ports]
# Background color of panel
background = "#1e1e2e"
# Border color
border = "#7f849c"
# Chart title - only whilst container is running, paused & stopped will use colors.container_state
title = "#a6e3a1"
# Private/Public/IP headings
headings = "#f9e2af"
# Ports & IP listing text
text = "#cdd6f4"

# The help popup
[colors.popup_help]
# Background color
background = "#1e1e2e"
# Text color
text = "#cdd6f4"
# Highlighted text color
text_highlight = "#b4befe"

# The info popup - used to display small messages - such as saving logs to disk, or change of mouse capture settings
[colors.popup_info]
# Background color
background = "#89b4fa"
# Text color
text = "#1e1e2e"

# The delete popup - used to display a confirmation warning when about to delete a container
[colors.popup_delete]
# Background color
background = "#313244"
# Text color
text = "#cdd6f4"
# Highlighted text color
text_highlight = "#f38ba8"

# The error popup - hopefully you'll never have to see this
[colors.popup_error]
# Background color
background = "#f38ba8"
# Text color
text = "#1e1e2e"
