"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 30
command_timeout = 1000

[directory]
home_symbol = '󰋞'

[aws]
symbol = ' '
format = 'on [$symbol($profile)( · $region)( · $duration) ]($style)'

[gcloud]
symbol = " "

[git_branch]
symbol = ' '

[golang]
symbol = ' '

[dotnet]
symbol = ' '

[terraform]
symbol = ' '
