"$schema" = 'https://starship.rs/config-schema.json'

format = '$git_branch$git_commit$git_state$git_metrics$git_status'

[git_branch]
symbol = ' '

[git_commit]
tag_disabled = false

[git_status]
format = '[󰄽 $all_status$ahead_behind 󰄾]($style) '
